export const env = {
  API_BASE_URL: process.env.NEXT_PUBLIC_API_URL || "http://localhost:3001",
  FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID:
    process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,
  USE_FIREBASE_EMULATOR: process.env.NEXT_PUBLIC_USE_FIREBASE_EMULATOR,
  FIREBASE_AUTH_EMULATOR_HOST:
    process.env.NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST,
  FIREBASE_AUTH_EMULATOR_PORT:
    process.env.NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_PORT,
  FIREBASE_FIRESTORE_EMULATOR_HOST:
    process.env.NEXT_PUBLIC_FIREBASE_FIRESTORE_EMULATOR_HOST,
  FIREBASE_FIRESTORE_EMULATOR_PORT:
    process.env.NEXT_PUBLIC_FIREBASE_FIRESTORE_EMULATOR_PORT,
};
